ccflags-y := -Iinclude/drm
obj-$(CONFIG_DRM_VCRTCM) := vcrtcm.o
vcrtcm-objs := vcrtcm_pcon.o vcrtcm_vblank.o vcrtcm_alloc.o vcrtcm_ioctl.o vcrtcm_module.o vcrtcm_p.o vcrtcm_g.o vcrtcm_utils.o vcrtcm_sysfs.o vcrtcm_pim_table.o vcrtcm_pcon_table.o
