ccflags-y := -Iinclude/drm -Iinclude/drm/vcrtcm
obj-$(CONFIG_DRM_VCRTCM) := vcrtcm.o
vcrtcm-objs := vcrtcm_module.o vcrtcm_pcon_methods.o vcrtcm_gpu_methods.o vcrtcm_utils.o vcrtcm_sysfs.o pimmgr_main.o pimmgr_ioctl.o pimmgr_structures.o pimmgr_sysfs.o
